#!/bin/bash

source "$CONFIG_DIR/colors.sh"

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

bar_bottom=(
  padding_left=0
  padding_right=0
  position=bottom
  height=45
  corner_radius=8
  blur_radius=30
  margin=12
  y_offset=6
  shadow=true
  color=$BAR_COLOR
  border_color=0xffc8c093
  border_width=2
)

bottom_bar --bar "${bar_bottom[@]}"

default=(
  padding_left=5
  padding_right=5
  icon.font="SF Pro:Semibold:14.0"
  label.font="SF Pro:Semibold:13.0"
  icon.color=$WHITE
  label.color=$WHITE
  background.color=$ITEM_BG_COLOR
  background.corner_radius=5
  icon.padding_left=9
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=9
)

bottom_bar --default "${default[@]}"

# Left items
source "$ITEM_DIR/spaces.sh"

# Center items
source "$ITEM_DIR/spotify.sh"

# Right items
source "$ITEM_DIR/cpu.sh"
source "$ITEM_DIR/temperature.sh"
source "$ITEM_DIR/ram.sh"
source "$ITEM_DIR/disk.sh"
source "$ITEM_DIR/netspeed.sh"
source "$ITEM_DIR/filler.sh"


bottom_bar --update
 
